### ISSUE TITLE
 ngx_http_lua_module版本问题

### ISSUE THREAD

**Issue by kroyoo** [oneinstack/ngx_lua_waf#12]
使用addons.sh安装ngx_lua_waf模块，ngx_http_lua_module默认版本都是 0.10.15，重启nginx查看日志会发现有一下错误，nginx服务可以正常使用。查看include/ngx_lua_waf.sh，看到${lua_nginx_module_ver}
` nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: /usr/local/nginx/conf/waf/resty/core/base.lua:24: ngx_http_lua_module 0.10.16 or 0.10.17 required)`

Centos7系统：
`NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
`

nginx信息
`nginx -V
nginx version: nginx/1.18.0
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
built with OpenSSL 1.1.1j  16 Feb 2021
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --user=www --group=www --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-http_mp4_module --with-openssl=../openssl-1.1.1j --with-pcre=../pcre-8.44 --with-pcre-jit --with-ld-opt=-ljemalloc --with-ld-opt=-Wl,-rpath,/usr/local/lib **--add-module=../lua-nginx-module-0.10.15** --add-module=../ngx_devel_kit
`

**Comment by kroyoo** [comment]
重开吧

**Comment by kroyoo** [comment]
由于waf/resty/core/base.lua中的`ngx_lua_v ~= 10016 and ngx_lua_v ~= 10017`和安装文件version.txt中的版本不匹配，导致nginx启动失败，建议改成最新版本、或者是否可以采用“大于等于”的策略。
`
nginx -V
nginx version: nginx/1.20.0
built by gcc 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --user=www --group=www --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_ssl_module --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-http_mp4_module --with-openssl=../openssl-1.1.1k --with-pcre=../pcre-8.44 --with-pcre-jit --with-ld-opt=-ljemalloc --with-ld-opt=-Wl,-rpath,/usr/local/lib --add-module=../lua-nginx-module-0.10.19 --add-module=../ngx_devel_kit --add-module=../ip2location-nginx --add-module=../ngx_http_geoip2_module
`

错误提示：
![image](https://user-images.githubusercontent.com/61957721/118239719-5ec42780-b457-11eb-8ccc-e8158819d894.png)

**Comment by oneinstack** [comment]
已经升级至最新
