### ISSUE TITLE
oneinstack用户，php7.3+phalcon做api时常被ban，求文档

### ISSUE THREAD

**Issue by yueim** [oneinstack/ngx_lua_waf#2]
用oneinstack很久了。
新近安装的实例，php7.3+phalcon做rest api server，启用了waf。
时常在点击的时候，跳转到 ```/captcha-waf.html?continue=a.....```
看过配置文件，只有一个
```config_cc_rate = "60/60"```
可能会影响这个，但点击频率绝对没有到达60次/分钟。
目前这个模块没有相关文档，
求指点，怎么适当放宽，避免出现 ```/captcha-waf.html?continue=a.....```

**Comment by oneinstack** [comment]
如果nginx waf和php在一台服务器，可能有php内部跳转，这种也会计数的，建议调大点，如果nginx waf只做方向代理是正常的

**Comment by yueim** [comment]
谢谢回复。
就是在一台服务器。nginx+apach+php-fpm。
